import {
  REPOS_ADD,
  REPOS_ERROR,
  REPOS_FETCH
} from './constants'
import reducer from './reducer'
import initState from './initState'

describe('repos reducer', () => {
  const repos = [
    {
      id: 90482094,
      node_id: 'MDEwOlJlcG9zaXRvcnk5MDQ4MjA5NA==',
      name: 'demo-calendar',
      full_name: 'marinsokol/demo-calendar',
      owner: {
        login: 'marinsokol',
        id: 15654942,
        node_id: 'MDQ6VXNlcjE1NjU0OTQy',
        avatar_url: 'https://avatars2.githubusercontent.com/u/15654942?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/marinsokol',
        html_url: 'https://github.com/marinsokol',
        followers_url: 'https://api.github.com/users/marinsokol/followers',
        following_url: 'https://api.github.com/users/marinsokol/following{/other_user}',
        gists_url: 'https://api.github.com/users/marinsokol/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/marinsokol/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/marinsokol/subscriptions',
        organizations_url: 'https://api.github.com/users/marinsokol/orgs',
        repos_url: 'https://api.github.com/users/marinsokol/repos',
        events_url: 'https://api.github.com/users/marinsokol/events{/privacy}',
        received_events_url: 'https://api.github.com/users/marinsokol/received_events',
        type: 'User',
        site_admin: false
      },
      private: false,
      html_url: 'https://github.com/marinsokol/demo-calendar',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/marinsokol/demo-calendar',
      forks_url: 'https://api.github.com/repos/marinsokol/demo-calendar/forks',
      keys_url: 'https://api.github.com/repos/marinsokol/demo-calendar/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/marinsokol/demo-calendar/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/marinsokol/demo-calendar/teams',
      hooks_url: 'https://api.github.com/repos/marinsokol/demo-calendar/hooks',
      issue_events_url: 'https://api.github.com/repos/marinsokol/demo-calendar/issues/events{/number}',
      events_url: 'https://api.github.com/repos/marinsokol/demo-calendar/events',
      assignees_url: 'https://api.github.com/repos/marinsokol/demo-calendar/assignees{/user}',
      branches_url: 'https://api.github.com/repos/marinsokol/demo-calendar/branches{/branch}',
      tags_url: 'https://api.github.com/repos/marinsokol/demo-calendar/tags',
      blobs_url: 'https://api.github.com/repos/marinsokol/demo-calendar/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/marinsokol/demo-calendar/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/marinsokol/demo-calendar/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/marinsokol/demo-calendar/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/marinsokol/demo-calendar/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/marinsokol/demo-calendar/languages',
      stargazers_url: 'https://api.github.com/repos/marinsokol/demo-calendar/stargazers',
      contributors_url: 'https://api.github.com/repos/marinsokol/demo-calendar/contributors',
      subscribers_url: 'https://api.github.com/repos/marinsokol/demo-calendar/subscribers',
      subscription_url: 'https://api.github.com/repos/marinsokol/demo-calendar/subscription',
      commits_url: 'https://api.github.com/repos/marinsokol/demo-calendar/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/marinsokol/demo-calendar/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/marinsokol/demo-calendar/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/marinsokol/demo-calendar/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/marinsokol/demo-calendar/contents/{+path}',
      compare_url: 'https://api.github.com/repos/marinsokol/demo-calendar/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/marinsokol/demo-calendar/merges',
      archive_url: 'https://api.github.com/repos/marinsokol/demo-calendar/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/marinsokol/demo-calendar/downloads',
      issues_url: 'https://api.github.com/repos/marinsokol/demo-calendar/issues{/number}',
      pulls_url: 'https://api.github.com/repos/marinsokol/demo-calendar/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/marinsokol/demo-calendar/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/marinsokol/demo-calendar/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/marinsokol/demo-calendar/labels{/name}',
      releases_url: 'https://api.github.com/repos/marinsokol/demo-calendar/releases{/id}',
      deployments_url: 'https://api.github.com/repos/marinsokol/demo-calendar/deployments',
      created_at: '2017-05-06T18:10:13Z',
      updated_at: '2017-05-07T20:54:20Z',
      pushed_at: '2017-05-07T20:59:43Z',
      git_url: 'git://github.com/marinsokol/demo-calendar.git',
      ssh_url: 'git@github.com:marinsokol/demo-calendar.git',
      clone_url: 'https://github.com/marinsokol/demo-calendar.git',
      svn_url: 'https://github.com/marinsokol/demo-calendar',
      homepage: null,
      size: 3447,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'HTML',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 118118458,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMTgxMTg0NTg=',
      name: 'dump-days-graphql',
      full_name: 'marinsokol/dump-days-graphql',
      owner: {
        login: 'marinsokol',
        id: 15654942,
        node_id: 'MDQ6VXNlcjE1NjU0OTQy',
        avatar_url: 'https://avatars2.githubusercontent.com/u/15654942?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/marinsokol',
        html_url: 'https://github.com/marinsokol',
        followers_url: 'https://api.github.com/users/marinsokol/followers',
        following_url: 'https://api.github.com/users/marinsokol/following{/other_user}',
        gists_url: 'https://api.github.com/users/marinsokol/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/marinsokol/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/marinsokol/subscriptions',
        organizations_url: 'https://api.github.com/users/marinsokol/orgs',
        repos_url: 'https://api.github.com/users/marinsokol/repos',
        events_url: 'https://api.github.com/users/marinsokol/events{/privacy}',
        received_events_url: 'https://api.github.com/users/marinsokol/received_events',
        type: 'User',
        site_admin: false
      },
      private: false,
      html_url: 'https://github.com/marinsokol/dump-days-graphql',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/marinsokol/dump-days-graphql',
      forks_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/forks',
      keys_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/teams',
      hooks_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/hooks',
      issue_events_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/issues/events{/number}',
      events_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/events',
      assignees_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/assignees{/user}',
      branches_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/branches{/branch}',
      tags_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/tags',
      blobs_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/languages',
      stargazers_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/stargazers',
      contributors_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/contributors',
      subscribers_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/subscribers',
      subscription_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/subscription',
      commits_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/contents/{+path}',
      compare_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/merges',
      archive_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/downloads',
      issues_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/issues{/number}',
      pulls_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/labels{/name}',
      releases_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/releases{/id}',
      deployments_url: 'https://api.github.com/repos/marinsokol/dump-days-graphql/deployments',
      created_at: '2018-01-19T11:41:09Z',
      updated_at: '2018-01-19T12:32:24Z',
      pushed_at: '2018-02-23T08:26:14Z',
      git_url: 'git://github.com/marinsokol/dump-days-graphql.git',
      ssh_url: 'git@github.com:marinsokol/dump-days-graphql.git',
      clone_url: 'https://github.com/marinsokol/dump-days-graphql.git',
      svn_url: 'https://github.com/marinsokol/dump-days-graphql',
      homepage: null,
      size: 49,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 49864392,
      node_id: 'MDEwOlJlcG9zaXRvcnk0OTg2NDM5Mg==',
      name: 'hkkc2016',
      full_name: 'marinsokol/hkkc2016',
      owner: {
        login: 'marinsokol',
        id: 15654942,
        node_id: 'MDQ6VXNlcjE1NjU0OTQy',
        avatar_url: 'https://avatars2.githubusercontent.com/u/15654942?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/marinsokol',
        html_url: 'https://github.com/marinsokol',
        followers_url: 'https://api.github.com/users/marinsokol/followers',
        following_url: 'https://api.github.com/users/marinsokol/following{/other_user}',
        gists_url: 'https://api.github.com/users/marinsokol/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/marinsokol/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/marinsokol/subscriptions',
        organizations_url: 'https://api.github.com/users/marinsokol/orgs',
        repos_url: 'https://api.github.com/users/marinsokol/repos',
        events_url: 'https://api.github.com/users/marinsokol/events{/privacy}',
        received_events_url: 'https://api.github.com/users/marinsokol/received_events',
        type: 'User',
        site_admin: false
      },
      private: false,
      html_url: 'https://github.com/marinsokol/hkkc2016',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/marinsokol/hkkc2016',
      forks_url: 'https://api.github.com/repos/marinsokol/hkkc2016/forks',
      keys_url: 'https://api.github.com/repos/marinsokol/hkkc2016/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/marinsokol/hkkc2016/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/marinsokol/hkkc2016/teams',
      hooks_url: 'https://api.github.com/repos/marinsokol/hkkc2016/hooks',
      issue_events_url: 'https://api.github.com/repos/marinsokol/hkkc2016/issues/events{/number}',
      events_url: 'https://api.github.com/repos/marinsokol/hkkc2016/events',
      assignees_url: 'https://api.github.com/repos/marinsokol/hkkc2016/assignees{/user}',
      branches_url: 'https://api.github.com/repos/marinsokol/hkkc2016/branches{/branch}',
      tags_url: 'https://api.github.com/repos/marinsokol/hkkc2016/tags',
      blobs_url: 'https://api.github.com/repos/marinsokol/hkkc2016/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/marinsokol/hkkc2016/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/marinsokol/hkkc2016/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/marinsokol/hkkc2016/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/marinsokol/hkkc2016/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/marinsokol/hkkc2016/languages',
      stargazers_url: 'https://api.github.com/repos/marinsokol/hkkc2016/stargazers',
      contributors_url: 'https://api.github.com/repos/marinsokol/hkkc2016/contributors',
      subscribers_url: 'https://api.github.com/repos/marinsokol/hkkc2016/subscribers',
      subscription_url: 'https://api.github.com/repos/marinsokol/hkkc2016/subscription',
      commits_url: 'https://api.github.com/repos/marinsokol/hkkc2016/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/marinsokol/hkkc2016/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/marinsokol/hkkc2016/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/marinsokol/hkkc2016/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/marinsokol/hkkc2016/contents/{+path}',
      compare_url: 'https://api.github.com/repos/marinsokol/hkkc2016/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/marinsokol/hkkc2016/merges',
      archive_url: 'https://api.github.com/repos/marinsokol/hkkc2016/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/marinsokol/hkkc2016/downloads',
      issues_url: 'https://api.github.com/repos/marinsokol/hkkc2016/issues{/number}',
      pulls_url: 'https://api.github.com/repos/marinsokol/hkkc2016/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/marinsokol/hkkc2016/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/marinsokol/hkkc2016/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/marinsokol/hkkc2016/labels{/name}',
      releases_url: 'https://api.github.com/repos/marinsokol/hkkc2016/releases{/id}',
      deployments_url: 'https://api.github.com/repos/marinsokol/hkkc2016/deployments',
      created_at: '2016-01-18T08:58:44Z',
      updated_at: '2016-01-18T09:14:43Z',
      pushed_at: '2016-05-04T16:45:24Z',
      git_url: 'git://github.com/marinsokol/hkkc2016.git',
      ssh_url: 'git@github.com:marinsokol/hkkc2016.git',
      clone_url: 'https://github.com/marinsokol/hkkc2016.git',
      svn_url: 'https://github.com/marinsokol/hkkc2016',
      homepage: null,
      size: 31249,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'CSS',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      open_issues_count: 0,
      license: null,
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 107029531,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDcwMjk1MzE=',
      name: 'mac-reload',
      full_name: 'marinsokol/mac-reload',
      owner: {
        login: 'marinsokol',
        id: 15654942,
        node_id: 'MDQ6VXNlcjE1NjU0OTQy',
        avatar_url: 'https://avatars2.githubusercontent.com/u/15654942?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/marinsokol',
        html_url: 'https://github.com/marinsokol',
        followers_url: 'https://api.github.com/users/marinsokol/followers',
        following_url: 'https://api.github.com/users/marinsokol/following{/other_user}',
        gists_url: 'https://api.github.com/users/marinsokol/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/marinsokol/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/marinsokol/subscriptions',
        organizations_url: 'https://api.github.com/users/marinsokol/orgs',
        repos_url: 'https://api.github.com/users/marinsokol/repos',
        events_url: 'https://api.github.com/users/marinsokol/events{/privacy}',
        received_events_url: 'https://api.github.com/users/marinsokol/received_events',
        type: 'User',
        site_admin: false
      },
      private: false,
      html_url: 'https://github.com/marinsokol/mac-reload',
      description: 'Chrome extension that adds pull to reload functionality to Chrome',
      fork: true,
      url: 'https://api.github.com/repos/marinsokol/mac-reload',
      forks_url: 'https://api.github.com/repos/marinsokol/mac-reload/forks',
      keys_url: 'https://api.github.com/repos/marinsokol/mac-reload/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/marinsokol/mac-reload/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/marinsokol/mac-reload/teams',
      hooks_url: 'https://api.github.com/repos/marinsokol/mac-reload/hooks',
      issue_events_url: 'https://api.github.com/repos/marinsokol/mac-reload/issues/events{/number}',
      events_url: 'https://api.github.com/repos/marinsokol/mac-reload/events',
      assignees_url: 'https://api.github.com/repos/marinsokol/mac-reload/assignees{/user}',
      branches_url: 'https://api.github.com/repos/marinsokol/mac-reload/branches{/branch}',
      tags_url: 'https://api.github.com/repos/marinsokol/mac-reload/tags',
      blobs_url: 'https://api.github.com/repos/marinsokol/mac-reload/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/marinsokol/mac-reload/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/marinsokol/mac-reload/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/marinsokol/mac-reload/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/marinsokol/mac-reload/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/marinsokol/mac-reload/languages',
      stargazers_url: 'https://api.github.com/repos/marinsokol/mac-reload/stargazers',
      contributors_url: 'https://api.github.com/repos/marinsokol/mac-reload/contributors',
      subscribers_url: 'https://api.github.com/repos/marinsokol/mac-reload/subscribers',
      subscription_url: 'https://api.github.com/repos/marinsokol/mac-reload/subscription',
      commits_url: 'https://api.github.com/repos/marinsokol/mac-reload/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/marinsokol/mac-reload/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/marinsokol/mac-reload/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/marinsokol/mac-reload/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/marinsokol/mac-reload/contents/{+path}',
      compare_url: 'https://api.github.com/repos/marinsokol/mac-reload/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/marinsokol/mac-reload/merges',
      archive_url: 'https://api.github.com/repos/marinsokol/mac-reload/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/marinsokol/mac-reload/downloads',
      issues_url: 'https://api.github.com/repos/marinsokol/mac-reload/issues{/number}',
      pulls_url: 'https://api.github.com/repos/marinsokol/mac-reload/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/marinsokol/mac-reload/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/marinsokol/mac-reload/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/marinsokol/mac-reload/labels{/name}',
      releases_url: 'https://api.github.com/repos/marinsokol/mac-reload/releases{/id}',
      deployments_url: 'https://api.github.com/repos/marinsokol/mac-reload/deployments',
      created_at: '2017-10-15T16:35:39Z',
      updated_at: '2017-10-15T16:35:40Z',
      pushed_at: '2017-10-16T17:42:24Z',
      git_url: 'git://github.com/marinsokol/mac-reload.git',
      ssh_url: 'git@github.com:marinsokol/mac-reload.git',
      clone_url: 'https://github.com/marinsokol/mac-reload.git',
      svn_url: 'https://github.com/marinsokol/mac-reload',
      homepage: 'https://chrome.google.com/webstore/detail/mac-reload/jmjbompggjpodbaehpndnodaglngeoba',
      size: 638,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      open_issues_count: 0,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz'
      },
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    }
  ]

  it('reducer is defined', () => {
    expect(reducer).toBeDefined()
  })

  it('handles fetch action', () => {
    expect(reducer(initState, { type: REPOS_FETCH }))
      .toEqual({ ...initState, loading: true })
  })

  it('handles add action', () => {
    const action = {
      type: REPOS_ADD,
      payload: {
        username: 'test',
        data: repos
      }
    }

    expect(reducer(initState, action))
      .toEqual({
        ...initState,
        ...action.payload,
        loading: false
      })
  })

  it('handles error action', () => {
    const action = {
      type: REPOS_ERROR,
      payload: {
        username: 'test',
        error: 'test'
      }
    }

    expect(reducer(initState, action))
      .toEqual({
        ...initState,
        ...action.payload,
        data: [],
        loading: false
      })
  })
})
